const DATOS_ANALISIS = {
  "perfil": {
    "ocupacion": {
      "Estudiante": 24,
      "Trabajador": 12,
      "Ambos": 3,
      "Otro": 2
    },
    "edades": {
      "Menos de 18": 1,
      "18-25": 28,
      "26-35": 8,
      "36-50": 2,
      "Más de 50": 2
    },
    "frecuencia": {
      "Rara vez": 16,
      "Varias veces por semana": 12,
      "Todos los días": 9,
      "Nunca": 4
    }
  },
  "calificaciones": {
    "promedios": {
      "Puntualidad": 2.78,
      "Limpieza": 2.73,
      "Trato conductor": 3.61,
      "Comodidad": 2.9,
      "Seguridad": 3.32,
      "General": 3.08
    },
    "distribucion": {
      "1.0": 4,
      "2.0": 5,
      "3.0": 17,
      "4.0": 12,
      "5.0": 2
    }
  },
  "problemas": {
    "Retrasos": 31,
    "Falta de rutas": 23,
    "Mal estado de camiones": 22,
    "Falta de información": 9,
    "Inseguridad": 1,
    "Falta de aire acondicionado en tiempo de calor": 1
  },
  "patrones": {
    "horarios": {
      "6:00 a.m. – 8:00 a.m.": 15,
      "12:00 p.m. - 2:00 p.m.": 14,
      "10:00 a.m. - 12:00 p.m.": 10,
      "8:00 a.m. – 10:00 a.m.": 8,
      "2:00 p.m. - 4:00 p.m.": 7,
      "4:00 p.m. - 6:00 p.m.": 6,
      "6:00 p.m. - 8:00 p.m.": 3
    },
    "traslado": {
      "15 - 30 minutos": 19,
      "30 - 60 minutos": 11,
      "Menos de 15 minutos": 9,
      "Más de una hora": 1
    },
    "demanda": {
      "12:00 p.m. - 2:00 p.m.": 16,
      "6:00 a.m. – 8:00 a.m.": 14,
      "10:00 a.m. - 12:00 p.m.": 6,
      "4:00 p.m. - 6:00 p.m.": 1,
      "2:00 p.m. - 4:00 p.m.": 1,
      "8:00 a.m. – 10:00 a.m.": 1,
      "6:00 p.m. - 8:00 p.m.": 1
    },
    "proposito": {
      "Escuela": 18,
      "Trabajo": 9,
      "Otros": 7,
      "Compras": 6
    }
  },
  "rutas": {
    "Circuito 1 Allende - Laureles (Línea 1A o 1B)": 23,
    "Circuito 2 Tierra y Libertad - Jiménez (Línea 7)": 10,
    "Circuito 4 Sonora - Tierra Blanca (Línea 2-6)": 9,
    "Circuito 6 Deportiva - Fovissste": 6,
    "Circuito 7 Sonora Express": 5,
    "Circuito 3 Pueblo Viejo - Misioneros": 4,
    "Circuito 5 Tetanchopo - Jacarandas": 1
  },
  "costo": {
    "percepcion": {
      "Adecuado": 34,
      "Muy barato": 5,
      "Caro": 1
    },
    "gasto": {
      "De $10 a $20": 20,
      "Menos de $10": 12,
      "Más de $20": 8
    }
  },
  "resumen": {
    "total_respuestas": 41,
    "edad_promedio": 26.5,
    "calificacion_promedio": 3.08,
    "problema_frecuente": "Retrasos",
    "ruta_mas_usada": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
    "hora_pico": "12:00 p.m. - 2:00 p.m."
  },
  "respuestas": [
    {
      "ocupacion": "Estudiante",
      "edad": 21,
      "frecuencia": "Varias veces por semana",
      "proposito": "Otros",
      "horario": "4:00 p.m. - 6:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "4:00 p.m. - 6:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 4,
      "limpieza": 3,
      "trato": 3,
      "comodidad": 3,
      "seguridad": 4,
      "calificacion": 4
    },
    {
      "ocupacion": "Estudiante",
      "edad": 21,
      "frecuencia": "Varias veces por semana",
      "proposito": "Escuela",
      "horario": "10:00 a.m. - 12:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 4,
      "limpieza": 3,
      "trato": 5,
      "comodidad": 5,
      "seguridad": 4,
      "calificacion": 4
    },
    {
      "ocupacion": "Estudiante",
      "edad": 21,
      "frecuencia": "Varias veces por semana",
      "proposito": "Otros",
      "horario": "10:00 a.m. - 12:00 p.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Falta de rutas",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 4,
      "limpieza": 4,
      "trato": 5,
      "comodidad": 5,
      "seguridad": 5,
      "calificacion": 4
    },
    {
      "ocupacion": "Estudiante",
      "edad": 22,
      "frecuencia": "Rara vez",
      "proposito": "Trabajo",
      "horario": "10:00 a.m. - 12:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones, Falta de información",
      "costo": "Muy barato",
      "gasto": "Menos de $10",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 4,
      "comodidad": 4,
      "seguridad": 5,
      "calificacion": 4
    },
    {
      "ocupacion": "Estudiante",
      "edad": 26,
      "frecuencia": "Rara vez",
      "proposito": "Otros",
      "horario": "8:00 a.m. – 10:00 a.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "10:00 a.m. - 12:00 p.m.",
      "rutas": "Circuito 7 Sonora Express",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 1,
      "limpieza": 1,
      "trato": 3,
      "comodidad": 1,
      "seguridad": 3,
      "calificacion": 2
    },
    {
      "ocupacion": "Estudiante",
      "edad": 22,
      "frecuencia": "Rara vez",
      "proposito": "Escuela",
      "horario": "8:00 a.m. – 10:00 a.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "10:00 a.m. - 12:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Falta de información",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 1,
      "limpieza": 2,
      "trato": 4,
      "comodidad": 3,
      "seguridad": 2,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 25,
      "frecuencia": "Varias veces por semana",
      "proposito": "Escuela",
      "horario": "10:00 a.m. - 12:00 p.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B), Circuito 2 Tierra y Libertad - Jiménez (Línea 7)",
      "problemas": "Falta de rutas, Mal estado de camiones, Falta de información",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 4,
      "limpieza": 3,
      "trato": 4,
      "comodidad": 4,
      "seguridad": 4,
      "calificacion": 4
    },
    {
      "ocupacion": "Estudiante",
      "edad": 22,
      "frecuencia": "Rara vez",
      "proposito": "Escuela",
      "horario": "12:00 p.m. - 2:00 p.m., 2:00 p.m. - 4:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 2,
      "limpieza": 2,
      "trato": 3,
      "comodidad": 2,
      "seguridad": 3,
      "calificacion": 2
    },
    {
      "ocupacion": "Estudiante",
      "edad": 23,
      "frecuencia": "Nunca",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 4 Sonora - Tierra Blanca (Línea 2-6), Circuito 7 Sonora Express",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones, Falta de información",
      "costo": "Muy barato",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 1,
      "trato": 3,
      "comodidad": 2,
      "seguridad": 4,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 23,
      "frecuencia": "Rara vez",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 2,
      "trato": 3,
      "comodidad": 3,
      "seguridad": 4,
      "calificacion": 3
    },
    {
      "ocupacion": "Ambos",
      "edad": 22,
      "frecuencia": "Nunca",
      "proposito": "Otros",
      "horario": "6:00 a.m. – 8:00 a.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B), Circuito 2 Tierra y Libertad - Jiménez (Línea 7), Circuito 3 Pueblo Viejo - Misioneros, Circuito 4 Sonora - Tierra Blanca (Línea 2-6), Circuito 5 Tetanchopo - Jacarandas, Circuito 6 Deportiva - Fovissste, Circuito 7 Sonora Express",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones, Falta de información, Inseguridad",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 1,
      "limpieza": 4,
      "trato": 1,
      "comodidad": 1,
      "seguridad": 2,
      "calificacion": 1
    },
    {
      "ocupacion": "Estudiante",
      "edad": 21,
      "frecuencia": "Rara vez",
      "proposito": "Escuela",
      "horario": "8:00 a.m. – 10:00 a.m., 2:00 p.m. - 4:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B), Circuito 6 Deportiva - Fovissste",
      "problemas": "Retrasos, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 2,
      "limpieza": 2,
      "trato": 3,
      "comodidad": 2,
      "seguridad": 2,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 22,
      "frecuencia": "Nunca",
      "proposito": "Otros",
      "horario": "6:00 a.m. – 8:00 a.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 4,
      "limpieza": 4,
      "trato": 4,
      "comodidad": 4,
      "seguridad": 5,
      "calificacion": 5
    },
    {
      "ocupacion": "Estudiante",
      "edad": 24,
      "frecuencia": "Varias veces por semana",
      "proposito": "Escuela",
      "horario": "8:00 a.m. – 10:00 a.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "10:00 a.m. - 12:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 4,
      "limpieza": 1,
      "trato": 5,
      "comodidad": 2,
      "seguridad": 1,
      "calificacion": 1
    },
    {
      "ocupacion": "Estudiante",
      "edad": 20,
      "frecuencia": "Varias veces por semana",
      "proposito": "Escuela",
      "horario": "12:00 p.m. - 2:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "2:00 p.m. - 4:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Falta de información",
      "costo": "Muy barato",
      "gasto": "Menos de $10",
      "puntualidad": 3,
      "limpieza": 4,
      "trato": 5,
      "comodidad": 3,
      "seguridad": 5,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 21,
      "frecuencia": "Varias veces por semana",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Falta de rutas",
      "costo": "Muy barato",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 4,
      "trato": 2,
      "comodidad": 3,
      "seguridad": 5,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 22,
      "frecuencia": "Rara vez",
      "proposito": "Otros",
      "horario": "10:00 a.m. - 12:00 p.m., 2:00 p.m. - 4:00 p.m., 4:00 p.m. - 6:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "10:00 a.m. - 12:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B), Circuito 6 Deportiva - Fovissste",
      "problemas": "Retrasos, Falta de rutas",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 2,
      "limpieza": 2,
      "trato": 3,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 1
    },
    {
      "ocupacion": "Ambos",
      "edad": 27,
      "frecuencia": "Rara vez",
      "proposito": "Escuela",
      "horario": "12:00 p.m. - 2:00 p.m., 2:00 p.m. - 4:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "10:00 a.m. - 12:00 p.m.",
      "rutas": "Circuito 7 Sonora Express",
      "problemas": "Retrasos, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 1,
      "limpieza": 3,
      "trato": 3,
      "comodidad": 1,
      "seguridad": 1,
      "calificacion": 5
    },
    {
      "ocupacion": "Estudiante",
      "edad": 22,
      "frecuencia": "Todos los días",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B), Circuito 3 Pueblo Viejo - Misioneros, Circuito 4 Sonora - Tierra Blanca (Línea 2-6)",
      "problemas": "Retrasos, Mal estado de camiones, Falta de información",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 4,
      "limpieza": 3,
      "trato": 4,
      "comodidad": 4,
      "seguridad": 5,
      "calificacion": 4
    },
    {
      "ocupacion": "Estudiante",
      "edad": 25,
      "frecuencia": "Todos los días",
      "proposito": "Escuela",
      "horario": "8:00 a.m. – 10:00 a.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "10:00 a.m. - 12:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 2,
      "limpieza": 4,
      "trato": 5,
      "comodidad": 4,
      "seguridad": 4,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 15,
      "frecuencia": "Rara vez",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 4 Sonora - Tierra Blanca (Línea 2-6)",
      "problemas": "Falta de rutas",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 4,
      "limpieza": 3,
      "trato": 4,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 4
    },
    {
      "ocupacion": "Trabajador",
      "edad": 23,
      "frecuencia": "Todos los días",
      "proposito": "Trabajo",
      "horario": "10:00 a.m. - 12:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7)",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 3,
      "limpieza": 1,
      "trato": 1,
      "comodidad": 1,
      "seguridad": 3,
      "calificacion": 2
    },
    {
      "ocupacion": "Trabajador",
      "edad": 30,
      "frecuencia": "Rara vez",
      "proposito": "Trabajo",
      "horario": "8:00 a.m. – 10:00 a.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7)",
      "problemas": "Falta de rutas",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 3,
      "comodidad": 2,
      "seguridad": 2,
      "calificacion": 3
    },
    {
      "ocupacion": "Trabajador",
      "edad": 33,
      "frecuencia": "Varias veces por semana",
      "proposito": "Compras",
      "horario": "10:00 a.m. - 12:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "8:00 a.m. – 10:00 a.m.",
      "rutas": "Circuito 4 Sonora - Tierra Blanca (Línea 2-6)",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 4,
      "limpieza": 5,
      "trato": 5,
      "comodidad": 5,
      "seguridad": 4,
      "calificacion": 4
    },
    {
      "ocupacion": "Trabajador",
      "edad": 20,
      "frecuencia": "Rara vez",
      "proposito": "Compras",
      "horario": "8:00 a.m. – 10:00 a.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 6 Deportiva - Fovissste",
      "problemas": "Falta de rutas",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 4,
      "comodidad": 5,
      "seguridad": 3,
      "calificacion": 3
    },
    {
      "ocupacion": "Trabajador",
      "edad": 35,
      "frecuencia": "Varias veces por semana",
      "proposito": "Trabajo",
      "horario": "6:00 a.m. – 8:00 a.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "Más de una hora",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7), Circuito 6 Deportiva - Fovissste",
      "problemas": "Retrasos, Falta de rutas",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 4,
      "limpieza": 5,
      "trato": 5,
      "comodidad": 5,
      "seguridad": 5,
      "calificacion": 4
    },
    {
      "ocupacion": "Estudiante",
      "edad": 19,
      "frecuencia": "Varias veces por semana",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Mal estado de camiones",
      "costo": "Muy barato",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 2,
      "trato": 4,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 3
    },
    {
      "ocupacion": "Ambos",
      "edad": 25,
      "frecuencia": "Todos los días",
      "proposito": "Escuela",
      "horario": "8:00 a.m. – 10:00 a.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones, Falta de información",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 1,
      "limpieza": 1,
      "trato": 3,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 24,
      "frecuencia": "Rara vez",
      "proposito": "Compras",
      "horario": "10:00 a.m. - 12:00 p.m., 12:00 p.m. - 2:00 p.m., 2:00 p.m. - 4:00 p.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7)",
      "problemas": "Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 2,
      "trato": 2,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 3
    },
    {
      "ocupacion": "Trabajador",
      "edad": 35,
      "frecuencia": "Todos los días",
      "proposito": "Trabajo",
      "horario": "6:00 a.m. – 8:00 a.m., 12:00 p.m. - 2:00 p.m., 6:00 p.m. - 8:00 p.m.",
      "traslado": "30 - 60 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7), Circuito 4 Sonora - Tierra Blanca (Línea 2-6), Circuito 6 Deportiva - Fovissste",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones, Falta de información",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 2,
      "limpieza": 3,
      "trato": 5,
      "comodidad": 1,
      "seguridad": 1,
      "calificacion": 2
    },
    {
      "ocupacion": "Otro",
      "edad": 43,
      "frecuencia": "Rara vez",
      "proposito": "Compras",
      "horario": "10:00 a.m. - 12:00 p.m., 4:00 p.m. - 6:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7)",
      "problemas": "Retrasos",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 4,
      "comodidad": 2,
      "seguridad": 4,
      "calificacion": 3
    },
    {
      "ocupacion": "Trabajador",
      "edad": 59,
      "frecuencia": "Varias veces por semana",
      "proposito": "Compras",
      "horario": "10:00 a.m. - 12:00 p.m., 4:00 p.m. - 6:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 3 Pueblo Viejo - Misioneros, Circuito 4 Sonora - Tierra Blanca (Línea 2-6)",
      "problemas": "Retrasos, Falta de rutas",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 2,
      "limpieza": 4,
      "trato": 3,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 3
    },
    {
      "ocupacion": "Trabajador",
      "edad": 35,
      "frecuencia": "Todos los días",
      "proposito": "Trabajo",
      "horario": "6:00 a.m. – 8:00 a.m., 4:00 p.m. - 6:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 4 Sonora - Tierra Blanca (Línea 2-6), Circuito 7 Sonora Express",
      "problemas": "Retrasos, Falta de rutas",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 3,
      "comodidad": 4,
      "seguridad": 4,
      "calificacion": 2
    },
    {
      "ocupacion": "Trabajador",
      "edad": 40,
      "frecuencia": "Rara vez",
      "proposito": "Trabajo",
      "horario": "2:00 p.m. - 4:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Falta de rutas",
      "costo": "Caro",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 3,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 4
    },
    {
      "ocupacion": "Trabajador",
      "edad": 55,
      "frecuencia": "Varias veces por semana",
      "proposito": "Trabajo",
      "horario": "6:00 a.m. – 8:00 a.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 3 Pueblo Viejo - Misioneros, Circuito 4 Sonora - Tierra Blanca (Línea 2-6)",
      "problemas": "Retrasos, Falta de rutas",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 3,
      "limpieza": 2,
      "trato": 4,
      "comodidad": 4,
      "seguridad": 4,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 26,
      "frecuencia": "Todos los días",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m., 12:00 p.m. - 2:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Falta de rutas, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 2,
      "limpieza": 3,
      "trato": 3,
      "comodidad": 2,
      "seguridad": 2,
      "calificacion": 3
    },
    {
      "ocupacion": "Estudiante",
      "edad": 23,
      "frecuencia": "Rara vez",
      "proposito": "Otros",
      "horario": "12:00 p.m. - 2:00 p.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "12:00 p.m. - 2:00 p.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7)",
      "problemas": "Retrasos",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 3,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 4
    },
    {
      "ocupacion": "Otro",
      "edad": 23,
      "frecuencia": "Rara vez",
      "proposito": "Compras",
      "horario": "2:00 p.m. - 4:00 p.m., 4:00 p.m. - 6:00 p.m., 6:00 p.m. - 8:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "Menos de $10",
      "puntualidad": 3,
      "limpieza": 3,
      "trato": 4,
      "comodidad": 2,
      "seguridad": 3,
      "calificacion": 3
    },
    {
      "ocupacion": "Trabajador",
      "edad": 22,
      "frecuencia": "Nunca",
      "proposito": "",
      "horario": "",
      "traslado": "",
      "demanda": "",
      "rutas": "",
      "problemas": "",
      "costo": "",
      "gasto": "",
      "puntualidad": 3,
      "limpieza": 1,
      "trato": 5,
      "comodidad": 1,
      "seguridad": 3,
      "calificacion": null
    },
    {
      "ocupacion": "Trabajador",
      "edad": 23,
      "frecuencia": "Todos los días",
      "proposito": "Trabajo",
      "horario": "6:00 a.m. – 8:00 a.m., 6:00 p.m. - 8:00 p.m.",
      "traslado": "15 - 30 minutos",
      "demanda": "6:00 p.m. - 8:00 p.m.",
      "rutas": "Circuito 1 Allende - Laureles (Línea 1A o 1B)",
      "problemas": "Retrasos, Falta de rutas, Mal estado de camiones",
      "costo": "Adecuado",
      "gasto": "De $10 a $20",
      "puntualidad": 1,
      "limpieza": 2,
      "trato": 4,
      "comodidad": 3,
      "seguridad": 3,
      "calificacion": 1
    },
    {
      "ocupacion": "Estudiante",
      "edad": 25,
      "frecuencia": "Todos los días",
      "proposito": "Escuela",
      "horario": "6:00 a.m. – 8:00 a.m.",
      "traslado": "Menos de 15 minutos",
      "demanda": "6:00 a.m. – 8:00 a.m.",
      "rutas": "Circuito 2 Tierra y Libertad - Jiménez (Línea 7)",
      "problemas": "Retrasos, Falta de aire acondicionado en tiempo de calor",
      "costo": "Adecuado",
      "gasto": "Más de $20",
      "puntualidad": 3,
      "limpieza": 2,
      "trato": 4,
      "comodidad": 2,
      "seguridad": 3,
      "calificacion": 4
    }
  ]
};